In [0]:
from __future__ import print_function
from sklearn.datasets import fetch_openml
import numpy as np
np.random.seed(44)

In [0]:
data_dir = './data'
mnist = fetch_openml('mnist_784', version=1, data_home = data_dir)

In [3]:
len(np.unique(mnist.target))

10

In [0]:
from sklearn.svm import SVC

K = len(np.unique(mnist.target))

X = mnist.data
y = mnist.target

In [0]:
# scaling the features
# from sklearn.preprocessing import scale
# X_scaled = scale(X)

# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, train_size = 0.2 ,random_state = 10)


In [32]:
# linear model

model_linear = SVC(kernel='rbf')
model_linear.fit(X_train, y_train)



SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
# predict
y_pred = model_linear.predict(X_test)

In [34]:
# confusion matrix and accuracy

from sklearn import metrics
from sklearn.metrics import confusion_matrix
# accuracy
print("accuracy:", metrics.accuracy_score(y_true=y_test, y_pred=y_pred), "\n")

# cm
print(metrics.confusion_matrix(y_true=y_test, y_pred=y_pred))

accuracy: 0.9644285714285714 

[[2087    0    4    0    1    3    8    1    5    3]
 [   0 2260    9    4    2    2    2    1    3    1]
 [  15    4 2028    7    9    7    7   17   21    2]
 [   2    3   24 2059    2   29    3   17   19    2]
 [   5    2   11    0 1967    0    9    4    1   39]
 [   4   10    8   31    5 1790   16    1   14    2]
 [   5    5    6    0    4   19 1968    0    2    0]
 [   3   12   14    0   21    0    0 2161    6   36]
 [   6   15   14   18   10   17   13    2 1956    6]
 [   9    4    6   18   38    7    0   18   12 1977]]


In [0]:
import pickle
def save_model(model, model_path = './model/model.pkl'):
  with open(model_path, 'wb') as f:
    pickle.dump(model, f)

In [0]:
def load_model(model_path = './model/model.pkl'):
  with open(model_path, 'rb') as f:
    model = pickle.load(f)
  return model

In [0]:
save_model(model_linear)

In [0]:
model = load_model()

In [0]:
import cv2
image = cv2.imread('image.png', cv2.IMREAD_GRAYSCALE)
image = cv2.resize(image, (28,28))
# image = 255-image
# image = image/255.0
image= image.reshape(1, -1)

In [106]:
y_pred = model.predict(image)
y_pred

array(['2'], dtype=object)