# Numpy

In [1]:
import numpy as np

## Bài 1: Tạo vector 0 với kích thước 10

In [2]:
zero_vector = np.zeros(10)
zero_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Bài 2: Tạo vector 0 nhưng phần tử thứ 5 của vector bằng 1


In [3]:
vector1 = np.zeros(10)
vector1[5] = 1
vector1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

## Bài 3: Tạo vector với giá trị các phần tử theo thứ tự nằm trong khoảng từ 10 đến 50


In [4]:
vector2 = np.arange(10, 50)
vector2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Bài 4: Tạo vector và đảo ngược vector đó


In [5]:
vector3 = np.arange(10)
dao_nguoc_vector3 = vector3[::-1]
print(vector3)
print(dao_nguoc_vector3)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


## Bài 5: Tạo ma trận đơn vị kích thước 3x3


In [6]:
matrix1 = np.identity(3) #np.eye(3)
matrix1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Bài 6: Tạo ma trận kích thước 3x3 với giá trị các phần tử nguyên ngẫu nhiên trong khoảng 1 đến 100


In [7]:
matrix2 = np.random.randint(low = 1, high= 100, size = (3, 3))
matrix2

array([[63, 56, 31],
       [94, 21, 75],
       [24,  4, 97]])

## Bài 7: Tạo ma trận 10x10 với giá trị các phần tử nguyên ngẫu nhiên trong khoảng 1 đến 100 sau đó tìm giá trị nhỏ nhất và lớn nhất


In [8]:
matrix3 = np.random.randint(low = 1, high= 100, size = (10, 10))
min_matrix1, max_matrix1 = np.amin(matrix3), np.amax(matrix3)
print(matrix2)
print('Min : ', min_matrix1)
print('Max : ', max_matrix1)

[[63 56 31]
 [94 21 75]
 [24  4 97]]
Min :  1
Max :  99


## Tạo một vector kích thước 30 với các giá trị phần tử nguyên ngẫu nhiên trong khoảng 1 đến 100. Sau đó tính trung bình

In [9]:
vector4 = np.random.randint(low = 1, high = 100, size = 30)
mean_vector4 = vector4.mean()
mean_vector4

44.56666666666667

## Bài 9: Tạo ma trận 2 chiều với các giá trị các phần tử tại các cạnh của ma trận là 1. Các phần tử nằm bên trong bằng 0


In [10]:
matrix4 = np.zeros((5, 5))
matrix4[0, :], matrix4[-1, :], matrix4[:, 0], matrix4[:, -1] = 1, 1, 1, 1
matrix4

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Bài 10: Cho một ma trận kích thước tùy ý. Thêm border(cạnh viền giá trị bằng 0) bao xung quanh ma trận. (Note: Thêm vào chứ không ghì đè)


In [11]:
matrix5 = np.random.randint(low = 1, high= 100, size = (10, 7))
print(matrix5.shape)
zero_row = np.zeros((1, matrix5.shape[1]))
matrix5 = np.concatenate((zero_row, matrix5, zero_row), axis=0)

zero_col =  np.zeros((matrix5.shape[0], 1))
matrix5 = np.concatenate((zero_col, matrix5, zero_col), axis=1)
matrix5

(10, 7)


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 29., 85., 95., 89., 72., 74., 58.,  0.],
       [ 0., 98., 70., 80., 43., 84., 13., 75.,  0.],
       [ 0., 66., 41., 84., 49., 78., 76.,  8.,  0.],
       [ 0., 47.,  1., 24., 14., 13., 10., 91.,  0.],
       [ 0., 94., 25., 12., 55., 68., 40., 33.,  0.],
       [ 0.,  7., 67., 94., 22., 14., 99., 36.,  0.],
       [ 0., 82., 39., 32., 55., 97., 35., 67.,  0.],
       [ 0., 28., 92., 46., 43.,  1., 46., 50.,  0.],
       [ 0., 54.,  4., 25., 92., 70., 48., 28.,  0.],
       [ 0., 49.,  1., 98., 57., 64., 84., 76.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

## Bài 11: Tạo ma trận 0 kích thước 5x5.Với các phần tử nằm dưới đường chéo chính bằng 1, 2, 3, 4


In [12]:
matrix6 = np.diag(np.arange(0, 5))
matrix6

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

## Bài 12: Tạo vector kích thước 10 sau đó sắp xếp tăng và giảm dần

In [13]:
vector5 = np.random.randint(low = 1, high = 100, size = 10)
tangdan = np.sort(vector5)
giamdan = tangdan[::-1]
print(vector5)
print(tangdan)
print(giamdan)

[27 79  6 17 75 46 55 19 22 57]
[ 6 17 19 22 27 46 55 57 75 79]
[79 75 57 55 46 27 22 19 17  6]


## Bài 13: Tạo vector kích thước 10 với giá trị nằm trong khoảng từ 0 đến 1

In [14]:
vector6 = np.random.random(size = 10)
vector6

array([0.4065267 , 0.77383658, 0.07793868, 0.76888819, 0.26565375,
       0.81301198, 0.26732163, 0.96164454, 0.21350911, 0.64484393])