
- Survived : nominal - Categorical : Dự liệu dạng binary, không có ý nghĩa toán học. Không có thứ tự (Người được cứu sống và người không được cứu sống)

- Pclass  : Ordinal - Categorical :không có ý nghĩa toán học chỉ là địa vị xã hội thuộc nhóm nào, có thứ tự thứ bậc

- Name : Nominal - Categorical : Dự liệu dạng ký tự, không có thứ tự

- Sex : Ordinal - Categorical : Dự liệu dạng chữ, không có ý nghĩa toán học, có thứ tự ( dạng phân loại nhị phân )

- Age    : Continous-Numeric :Có nhận giá trị bất kỳ trong một khoảng xác định. (Có thể thuộc discrete vì khoảng cách không quá nhỏ)

- SibSp :  discrete - Numeric: Số người quan hệ trong họ hàng 

- Ticket: Nominal - Categorical : Dự liệu dạng ký tự, phân loại không có thứ tự

- Fare   : Continous-Numeric :Có nhận giá trị bất kỳ trong một khoảng xác định

- Cabin: Nominal - Categorical : Dự liệu dạng ký tự, không có thứ tự

- Embarked: Nominal - Categorical : Dự liệu dạng chữ, không có ý nghĩa toán học, không có thứ tự vì S- Q- C không có gì liên quan đến nhau

In [1]:
import numpy as np
import pandas as pd

In [2]:
titanic_dataset = pd.read_csv('./Dataset/titanic.csv')

In [3]:
print(titanic_dataset.shape)
titanic_dataset.head(5)

(891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
titanic_dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Missing Value

In [5]:
X = titanic_dataset.values
X

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

### Age

In [6]:
from sklearn.impute import SimpleImputer

age_impute = SimpleImputer(np.nan, strategy = 'mean')
X[:, 5] = age_impute.fit_transform(X[:, 5].reshape(-1, 1)).ravel()
X

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

### Cabin

In [7]:
cabin_impute = SimpleImputer(np.nan, strategy = 'most_frequent') #mode
X[:, 10] = cabin_impute.fit_transform(X[:, 10].reshape(-1, 1)).ravel()
X

array([[1, 0, 3, ..., 7.25, 'B96 B98', 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 23.45, 'B96 B98', 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, 'B96 B98', 'Q']], dtype=object)

### Embarked

In [8]:
Embarked_impute = SimpleImputer(np.nan, strategy = 'most_frequent') #mode
X[:, 11] = Embarked_impute.fit_transform(X[:, 11].reshape(-1, 1)).ravel()
X

array([[1, 0, 3, ..., 7.25, 'B96 B98', 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 23.45, 'B96 B98', 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, 'B96 B98', 'Q']], dtype=object)

In [9]:
titanic_dataset = pd.DataFrame.from_records(X, columns = titanic_dataset.columns)
titanic_dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare    Cabin Embarked  
0      0         A/5 21171   7.2500  B96 B98        S  
1      0          PC 17599  71.2833      C85        C  
2      0  STON/O2. 3101282   7.9250  B96 B98        S  
3      0            113803  53.1000     C123        S  
4      0            373450   8.0500  B96 B98        S

In [10]:
print(titanic_dataset.shape)
titanic_dataset.isnull().sum()

(891, 12)


PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# Chuẩn Hóa Dữ Liệu

In [11]:
X = titanic_dataset.values

### Fare

In [12]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
minmax_scaler_fare = MinMaxScaler()
X[:, 9] = minmax_scaler_fare.fit_transform(X[:, 9].reshape(-1, 1)).ravel()
X

array([[1, 0, 3, ..., 0.014151057562208049, 'B96 B98', 'S'],
       [2, 1, 1, ..., 0.13913573538264068, 'C85', 'C'],
       [3, 1, 3, ..., 0.015468569817999833, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 0.04577135170121086, 'B96 B98', 'S'],
       [890, 1, 1, ..., 0.05855610025741262, 'C148', 'C'],
       [891, 0, 3, ..., 0.015126992566498259, 'B96 B98', 'Q']],
      dtype=object)

### Sex

In [13]:
from sklearn.preprocessing import  LabelEncoder
sex_label_encoder = LabelEncoder()
X[:, 4] = sex_label_encoder.fit_transform(X[:, 4])
X

array([[1, 0, 3, ..., 0.014151057562208049, 'B96 B98', 'S'],
       [2, 1, 1, ..., 0.13913573538264068, 'C85', 'C'],
       [3, 1, 3, ..., 0.015468569817999833, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 0.04577135170121086, 'B96 B98', 'S'],
       [890, 1, 1, ..., 0.05855610025741262, 'C148', 'C'],
       [891, 0, 3, ..., 0.015126992566498259, 'B96 B98', 'Q']],
      dtype=object)

### Age

In [14]:
minmax_scaler_age = MinMaxScaler()
X[:, 5] = minmax_scaler_age.fit_transform(X[:, 5].reshape(-1, 1)).ravel()

### Embarked

In [15]:
from sklearn.preprocessing import OneHotEncoder

embarked_onehot = OneHotEncoder()
embarked = embarked_onehot.fit_transform(X[:, 11].reshape(-1, 1)).toarray()
X = np.delete(X, 11, axis = 1)
X = np.concatenate((X, embarked), axis = 1)
X

array([[1, 0, 3, ..., 0.0, 0.0, 1.0],
       [2, 1, 1, ..., 1.0, 0.0, 0.0],
       [3, 1, 3, ..., 0.0, 0.0, 1.0],
       ...,
       [889, 0, 3, ..., 0.0, 0.0, 1.0],
       [890, 1, 1, ..., 1.0, 0.0, 0.0],
       [891, 0, 3, ..., 0.0, 1.0, 0.0]], dtype=object)

# Chuẩn hóa cho quen

### name

In [16]:
from sklearn.preprocessing import  LabelEncoder
name_label_encoder = LabelEncoder()
X[:, 3] = name_label_encoder.fit_transform(X[:, 3])
X

array([[1, 0, 3, ..., 0.0, 0.0, 1.0],
       [2, 1, 1, ..., 1.0, 0.0, 0.0],
       [3, 1, 3, ..., 0.0, 0.0, 1.0],
       ...,
       [889, 0, 3, ..., 0.0, 0.0, 1.0],
       [890, 1, 1, ..., 1.0, 0.0, 0.0],
       [891, 0, 3, ..., 0.0, 1.0, 0.0]], dtype=object)

### Ticket

In [17]:
from sklearn.preprocessing import  LabelEncoder
ticket_label_encoder = LabelEncoder()
X[:, 8] = ticket_label_encoder.fit_transform(X[:, 8])
X

array([[1, 0, 3, ..., 0.0, 0.0, 1.0],
       [2, 1, 1, ..., 1.0, 0.0, 0.0],
       [3, 1, 3, ..., 0.0, 0.0, 1.0],
       ...,
       [889, 0, 3, ..., 0.0, 0.0, 1.0],
       [890, 1, 1, ..., 1.0, 0.0, 0.0],
       [891, 0, 3, ..., 0.0, 1.0, 0.0]], dtype=object)

### cabin

In [18]:
from sklearn.preprocessing import  LabelEncoder
cabin_label_encoder = LabelEncoder()
X[:, 10] = cabin_label_encoder.fit_transform(X[:, 10])
X

array([[1, 0, 3, ..., 0.0, 0.0, 1.0],
       [2, 1, 1, ..., 1.0, 0.0, 0.0],
       [3, 1, 3, ..., 0.0, 0.0, 1.0],
       ...,
       [889, 0, 3, ..., 0.0, 0.0, 1.0],
       [890, 1, 1, ..., 1.0, 0.0, 0.0],
       [891, 0, 3, ..., 0.0, 1.0, 0.0]], dtype=object)