- age : Continous-Numeric :Có nhận giá trị bất kỳ trong một khoảng xác định. (Có thể thuộc discrete vì khoảng cách không quá nhỏ)
- job: Nominal - Categorical : Dự liệu dạng ký tự, phân loại nghề nghiệp nên không có thứ tự
- marital : Ordinal - Categorical Dự liệu dạng chữ, không có ý nghĩa toán học, 2 kiểu là married hoặc single mà 2 cái này không có theo thứ tự nào cả
- education : Dự liệu dạng chữ, không có ý nghĩa toán học, có thứ tự theo từng cấp bậc học 
- balance : Continous-Numeric :Có nhận giá trị bất kỳ trong một khoảng xác định
- housing :norminal - Categorical : Dự liệu dạng chữ, không có ý nghĩa toán học( Yes - No ;  dạng nhị phân)
- loan : Ordinal - Categorical : Dự liệu dạng chữ, không có ý nghĩa toán học, không có thứ tự( Yes - No ; dạng nhị phân)
- contact : Ordinal - Categorical Dự liệu dạng chữ, không có ý nghĩa toán học, không có thứ tự vì có thể có thể liên lạc bằng cách khác nhau
- day : Ordinal - Categorical : Dự liệu theo ngày không có ý nghĩa toán học, có thứ tự vì ngày trong 1 tháng có thứ tự từ 1 -> 30
- month : Ordinal - Categorical : Dự liệu dạng chữ, không có ý nghĩa toán học, có thứ tự vì tháng theo thứ tự từ 1->12

In [1]:
import numpy as np
import pandas as pd

In [2]:
bank_dataset = pd.read_csv('./Dataset/bank.csv', sep = ';')
print(bank_dataset.shape)
bank_dataset.head(5)

(19, 10)


age          job  marital  education  balance housing loan   contact  day  \
0   30   unemployed  married    primary     1787      no   no  cellular   19   
1   33     services      NaN  secondary     4789     yes  yes  cellular   11   
2   35   management   single        NaN     1350     yes   no  cellular   16   
3   30   management  married   tertiary     1476     NaN  yes   unknown    3   
4   59  blue-collar  married  secondary        0     yes   no   unknown    5   

  month  
0   oct  
1   may  
2   apr  
3   jun  
4   may

In [3]:
bank_dataset.isnull().sum()

age          0
job          1
marital      2
education    1
balance      0
housing      1
loan         0
contact      1
day          0
month        1
dtype: int64

# Missing Value

## job

In [4]:
X = bank_dataset.values

from sklearn.impute import SimpleImputer
job_impute = SimpleImputer(np.nan, strategy = 'most_frequent') #mode
X[:, 1] = job_impute.fit_transform(X[:, 1].reshape(-1, 1)).ravel()

### Marital

In [5]:
from sklearn.impute import SimpleImputer
marital_impute = SimpleImputer(np.nan, strategy = 'most_frequent') #mode
X[:, 2] = marital_impute.fit_transform(X[:, 2].reshape(-1, 1)).ravel()

### Education

In [6]:
from sklearn.impute import SimpleImputer
education_impute = SimpleImputer(np.nan, strategy = 'most_frequent') #mode
X[:, 3] = education_impute.fit_transform(X[:, 3].reshape(-1, 1)).ravel()

### Housing

In [7]:
from sklearn.impute import SimpleImputer
housing_impute = SimpleImputer(np.nan, strategy = 'most_frequent') #mode
X[:, 5] = housing_impute.fit_transform(X[:, 5].reshape(-1, 1)).ravel()

### Contact

In [8]:
from sklearn.impute import SimpleImputer
contact_impute = SimpleImputer(np.nan, strategy = 'most_frequent') #mode
X[:, 7] = contact_impute.fit_transform(X[:, 7].reshape(-1, 1)).ravel()

### Month

In [9]:
from sklearn.impute import SimpleImputer
month_impute = SimpleImputer(np.nan, strategy = 'most_frequent') #mode
X[:, -1] = month_impute.fit_transform(X[:,-1].reshape(-1, 1)).ravel()

In [10]:
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, 'yes', 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39,

In [11]:
bank_dataset.isnull().sum()

age          0
job          1
marital      2
education    1
balance      0
housing      1
loan         0
contact      1
day          0
month        1
dtype: int64

In [12]:
bank_dataset = pd.DataFrame.from_records(X, columns = bank_dataset.columns)
bank_dataset.head()

age          job  marital  education  balance housing loan   contact  day  \
0   30   unemployed  married    primary     1787      no   no  cellular   19   
1   33     services  married  secondary     4789     yes  yes  cellular   11   
2   35   management   single  secondary     1350     yes   no  cellular   16   
3   30   management  married   tertiary     1476     yes  yes   unknown    3   
4   59  blue-collar  married  secondary        0     yes   no   unknown    5   

  month  
0   oct  
1   may  
2   apr  
3   jun  
4   may

# Chuẩn hóa dữ liệu

In [13]:
X = bank_dataset.values

In [14]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import  LabelEncoder

### age

In [15]:
minmax_scaler_age = MinMaxScaler()
X[:, 0] = minmax_scaler_age.fit_transform(X[:, 0].reshape(-1, 1)).ravel()

### balance

In [16]:
minmax_scaler_balance = MinMaxScaler()
X[:, 4] = minmax_scaler_balance.fit_transform(X[:, 4].reshape(-1, 1)).ravel()

### housing

In [17]:
housing_label_encoder = LabelEncoder()
X[:, 5] = housing_label_encoder.fit_transform(X[:, 5])

### loan

In [18]:
loan_label_encoder = LabelEncoder()
X[:, 6] = loan_label_encoder.fit_transform(X[:, 6])

### marital

In [19]:
marital_label_encoder = LabelEncoder()
X[:, 2] = marital_label_encoder.fit_transform(X[:, 2])
X

array([[0.2564102564102564, 'unemployed', 0, 'primary',
        0.20927566440854614, 0, 0, 'cellular', 19, 'oct'],
       [0.33333333333333337, 'services', 0, 'secondary',
        0.522146951537259, 1, 1, 'cellular', 11, 'may'],
       [0.3846153846153846, 'management', 1, 'secondary',
        0.16373110995310058, 1, 0, 'cellular', 16, 'apr'],
       [0.2564102564102564, 'management', 0, 'tertiary',
        0.17686294945284003, 1, 1, 'unknown', 3, 'jun'],
       [1.0, 'blue-collar', 0, 'secondary', 0.02303282959874935, 1, 0,
        'unknown', 5, 'may'],
       [0.3846153846153846, 'management', 1, 'tertiary',
        0.10088587806149035, 0, 0, 'cellular', 23, 'feb'],
       [0.41025641025641024, 'self-employed', 0, 'tertiary',
        0.05502866076081292, 1, 0, 'cellular', 14, 'may'],
       [0.4871794871794872, 'technician', 0, 'secondary',
        0.03835330901511204, 1, 0, 'cellular', 6, 'may'],
       [0.5384615384615385, 'entrepreneur', 0, 'tertiary',
        0.0460656591974987, 

In [20]:
from sklearn.preprocessing import OneHotEncoder

### Job

In [21]:
job_onehot = OneHotEncoder()
job = job_onehot.fit_transform(X[:, 1].reshape(-1, 1)).toarray()
X = np.delete(X, 1, axis = 1)
X = np.concatenate((X[:, 0:2], job, X[:, 2:]), axis = 1)
X

array([[0.2564102564102564, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 'primary', 0.20927566440854614, 0, 0, 'cellular', 19, 'oct'],
       [0.33333333333333337, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 'secondary', 0.522146951537259, 1, 1, 'cellular', 11, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 'secondary', 0.16373110995310058, 1, 0, 'cellular', 16,
        'apr'],
       [0.2564102564102564, 0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 'tertiary', 0.17686294945284003, 1, 1, 'unknown', 3, 'jun'],
       [1.0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'secondary',
        0.02303282959874935, 1, 0, 'unknown', 5, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 'tertiary', 0.10088587806149035, 0, 0, 'cellular', 23,
        'feb'],
       [0.41025641025641024, 0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.0, 'tertiary', 0.05502866076081292, 1,

### education

In [22]:
education_onehot = OneHotEncoder()
education = education_onehot.fit_transform(X[:, 11].reshape(-1, 1)).toarray()
X = np.delete(X, 11, axis = 1)
X = np.concatenate((X[:, 0:11], job, X[:, 11:]), axis = 1)
X

array([[0.2564102564102564, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.20927566440854614, 0, 0, 'cellular', 19, 'oct'],
       [0.33333333333333337, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.522146951537259, 1, 1, 'cellular', 11, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.16373110995310058, 1, 0, 'cellular', 16, 'apr'],
       [0.2564102564102564, 0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.17686294945284003, 1, 1, 'unknown', 3, 'jun'],
       [1.0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02303282959874935, 1, 0,
        'unknown', 5, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0

### Contact

In [23]:
contact_label_encoder = LabelEncoder()
X[:, -3] = contact_label_encoder.fit_transform(X[:, -3])
X

array([[0.2564102564102564, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.20927566440854614, 0, 0, 0, 19, 'oct'],
       [0.33333333333333337, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.522146951537259, 1, 1, 0, 11, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.16373110995310058, 1, 0, 0, 16, 'apr'],
       [0.2564102564102564, 0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.17686294945284003, 1, 1, 1, 3, 'jun'],
       [1.0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02303282959874935, 1, 0, 1,
        5, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,

### Month

In [24]:
month_label_encoder = LabelEncoder()
X[:, -1] = month_label_encoder.fit_transform(X[:, -1])
X

array([[0.2564102564102564, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.20927566440854614, 0, 0, 0, 19, 6],
       [0.33333333333333337, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.522146951537259, 1, 1, 0, 11, 5],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.16373110995310058, 1, 0, 0, 16, 0],
       [0.2564102564102564, 0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.17686294945284003, 1, 1, 1, 3, 4],
       [1.0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02303282959874935, 1, 0, 1,
        5, 5],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.1008